/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.QuanLyCanBoController;
import java.awt.CardLayout;
import javafx.collections.ObservableList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.CanBo;

/**
 *
 * @author Admin
 */
public class CapNhatPanel extends javax.swing.JPanel {

    /**
     * Creates new form JCapNhat
     */
    private static int option = -1; 
    
    public CapNhatPanel() {
        initComponents();
        String[] column = {"Họ và tên", "Mã cán bộ","Kiểu cán bộ","Ngày sinh","số công"};
        model = new DefaultTableModel(column, 0);
        this.updateTable.setModel(model);  
        this.inputPanel = new InputCapNhatPanel();
        
        this.add(this.MainPanel1, "main");
        this.add(this.inputPanel,"input");
        
        clOut = (CardLayout) this.getLayout();
        this.setLayout(clOut);
    }
    
    
    
    //set table
    public void setTable(ObservableList<CanBo> danhSachSinhVien){
        System.out.println("danh sach sinh vien: "+ danhSachSinhVien.isEmpty());
        String Ten,MaCanBo,KieuCanBo,NgaySinh,SoCong;
        for(CanBo cb: danhSachSinhVien){
//            CanBo cb = danhSachSinhVien.get(i);
            Ten = cb.getTen();
            MaCanBo = ""+cb.getMaCanBo();
            KieuCanBo = cb.getKieuCanBo();
            NgaySinh = cb.getNgaySinh();
            SoCong = cb.getCong();
            model.addRow(new Object[]{Ten,MaCanBo,KieuCanBo,NgaySinh, SoCong});
        }
    }

    public JButton getAddButton() {
        return addButton;
    }

    public JButton getDeleteButton() {
        return deleteButton;
    }

    public JButton getUpdateButton() {
        return updateButton;
    }

    public JScrollPane getCapNhatTable() {
        return capNhatTable;
    }

    public JTable getUpdateTable() {
        return updateTable;
    }
    
    public static int getOpton(){
        return option;
    }

    public static DefaultTableModel getModel() {
        return model;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel1 = new javax.swing.JPanel();
        capNhatTable = new javax.swing.JScrollPane();
        updateTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        timKiemText = new javax.swing.JTextField();
        timKiemButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(602, 248));
        setLayout(new java.awt.CardLayout());

        updateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        updateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTableMouseClicked(evt);
            }
        });
        capNhatTable.setViewportView(updateTable);

        addButton.setText("ADD");

        deleteButton.setText("Delete");

        updateButton.setText("Update");

        timKiemButton.setText("Tìm kiếm");
        timKiemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel1Layout = new javax.swing.GroupLayout(MainPanel1);
        MainPanel1.setLayout(MainPanel1Layout);
        MainPanel1Layout.setHorizontalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capNhatTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel1Layout.createSequentialGroup()
                        .addComponent(timKiemText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timKiemButton)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanel1Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(75, 75, 75)
                        .addComponent(deleteButton)
                        .addGap(67, 67, 67)
                        .addComponent(updateButton)
                        .addGap(104, 104, 104))))
        );
        MainPanel1Layout.setVerticalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemButton)
                    .addComponent(timKiemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(capNhatTable, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        add(MainPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void timKiemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemButtonActionPerformed
        // TODO add your handling code here:
        String infor = this.timKiemText.getText();
        String ten, maCanBo, kieuCanBo, ngaySinh, soCong;
        
        model.setRowCount(0);
        
        for(CanBo cb: QuanLyCanBoController.getInstance().timKiem(infor)){
            ten = cb.getTen();
            maCanBo = ""+cb.getMaCanBo();
            kieuCanBo = cb.getKieuCanBo();
            ngaySinh = ""+cb.getNgaySinh();
            soCong = cb.getCong();
            model.addRow(new Object[]{ten, maCanBo, kieuCanBo, ngaySinh, soCong});
        }
    }//GEN-LAST:event_timKiemButtonActionPerformed

    private void updateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTableMouseClicked
        // TODO add your handling code here:
        option = this.updateTable.getSelectedColumn();
    }//GEN-LAST:event_updateTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane capNhatTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton timKiemButton;
    private javax.swing.JTextField timKiemText;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable updateTable;
    // End of variables declaration//GEN-END:variables
    private static DefaultTableModel model;
    private InputCapNhatPanel inputPanel;
    private CardLayout clOut;
}
