/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.QuanLyCanBoController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import models.CanBo;

/**
 *
 * @author Admin
 */
public class InputCapNhatPanel extends javax.swing.JPanel {

    /**
     * Creates new form InputCapNhatPanel
     */
    
    private int selectedRow = CapNhatPanel.getOpton();
    private CanBo cb;
    public InputCapNhatPanel() {
        initComponents();
        this.idTextField.setEnabled(false);
        this.setAllTextFieldEnable(false);
    }
    
    public void setAllTextFileContent(String Ten, String maCanBo, String NgaySinh ,String kieuCanBo, String soCong){
        this.nameTextField.setText(Ten);
        this.idTextField.setText(maCanBo);
        this.ngaySinhTextField.setText(NgaySinh);
        int choosen;
            switch(kieuCanBo){
            case "GiaoVien" -> {
                choosen = 0;
            }
            case "CanBoTapVu" -> {
                choosen = 1;
            }
            case "CanBoNghienCuu" -> {
                choosen = 2;
            }
            default -> choosen = -1;
        }
        this.typeComboBox.setSelectedIndex(choosen);
        this.soCongTextField.setText(soCong);
    }
    
    public void setAllTextFieldEnable(boolean status){
        this.idTextField.setEnabled(status);
        this.kieuCanBojLabel1.setEnabled(status);
        this.ngaySinhTextField.setEnabled(status);
        this.nameTextField.setEnabled(status);
        this.soCongTextField.setEnabled(status);
    }
    
    public JButton getTextButton(){
        return this.updatejButton1;
    }
    
    public void setOptionTitle(String title){
        this.updatejButton1.setText(title);
    }
    
    public void setSelectedRow(int selectedRow){
        this.selectedRow = selectedRow;
    }
    
    public int getSelectedRow(){
        return this.selectedRow;
    }

    public JTextField getIdTextField() {
        return idTextField;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public JTextField getNgaySinhTextField() {
        return ngaySinhTextField;
    }

    public JTextField getSoCongTextField() {
        return soCongTextField;
    }

    public JComboBox<String> getTypeComboBox() {
        return typeComboBox;
    }

    public CanBo getCb() {
        return cb;
    }

    public JLabel getTenLabel() {
        return TenLabel;
    }


    public JLabel getIdJLabel1() {
        return idJLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getKieuCanBojLabel1() {
        return kieuCanBojLabel1;
    }

    public JLabel getNgaySinhLabel() {
        return ngaySinhLabel;
    }

    public JButton getUpdatejButton1() {
        return updatejButton1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TenLabel = new javax.swing.JLabel();
        idJLabel1 = new javax.swing.JLabel();
        kieuCanBojLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        soCongTextField = new javax.swing.JTextField();
        updatejButton1 = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        ngaySinhLabel = new javax.swing.JLabel();
        ngaySinhTextField = new javax.swing.JTextField();

        TenLabel.setText("name");

        idJLabel1.setText("id");

        kieuCanBojLabel1.setText("Kieu can bo");

        jLabel2.setText("so cong");

        updatejButton1.setText("text");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GiaoVien", "CanBoTapVu", "CanBoNghienCuu" }));

        ngaySinhLabel.setText("ngay sinh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kieuCanBojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngaySinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(nameTextField)
                    .addComponent(typeComboBox, 0, 223, Short.MAX_VALUE)
                    .addComponent(soCongTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(ngaySinhTextField))
                .addGap(18, 18, 18)
                .addComponent(updatejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatejButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(soCongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kieuCanBojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TenLabel;
    private javax.swing.JLabel idJLabel1;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kieuCanBojLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JTextField ngaySinhTextField;
    private javax.swing.JTextField soCongTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JButton updatejButton1;
    // End of variables declaration//GEN-END:variables

}
