/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javafx.collections.ObservableList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.CanBo;

/**
 *
 * @author Admin
 */
public class LocCanBoNghienCuuJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeJPanel
     */
    public LocCanBoNghienCuuJPanel1() {
        initComponents();
        String[] column = {"Tên","ID","ngày Sinh", "số Báo cáo"};
        thongKeModel = new DefaultTableModel(column,0);
        this.thongKeTable1.setModel(thongKeModel);
        this.thongKeTable1.setEnabled(false);
    }
    
    public int setTableContent(ObservableList<CanBo> danhSachCanBo){
        if(danhSachCanBo == null) return 0;
        String Ten,Id,NgaySinh,SoCong;
        for(CanBo cb: danhSachCanBo){
            Ten = cb.getTen();
            Id = ""+cb.getMaCanBo();
            NgaySinh = cb.getNgaySinh();
            SoCong = cb.getCong();
            thongKeModel.addRow(new Object[]{Ten,Id,NgaySinh,SoCong});
        }
        return 1;
    }
    
    public void removeAllRow(){
        thongKeModel.setRowCount(0);
    }

    public JButton getLocButton() {
        return locButton;
    }

    public JTextField getLocTextField() {
        return locTextField;
    }

    public JTable getThongKeTable1() {
        return thongKeTable1;
    }
    
  

    public JScrollPane getThongKeScrollPane() {
        return thongKeScrollPane;
    }

    public static DefaultTableModel getThongKeModel() {
        return thongKeModel;
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thongKeScrollPane = new javax.swing.JScrollPane();
        thongKeTable1 = new javax.swing.JTable();
        locTextField = new javax.swing.JTextField();
        locButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(602, 248));

        thongKeTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        thongKeScrollPane.setViewportView(thongKeTable1);

        locButton.setText("Lọc");
        locButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thongKeScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(locTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locButton)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongKeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton locButton;
    private javax.swing.JTextField locTextField;
    private javax.swing.JScrollPane thongKeScrollPane;
    private javax.swing.JTable thongKeTable1;
    // End of variables declaration//GEN-END:variables
    private static DefaultTableModel thongKeModel;
}
