/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javafx.collections.ObservableList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.CanBo;

/**
 *
 * @author Admin
 */
public class ThongKeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
        String[] column = {"Tên","ID","ngày Sinh", "số công"};
        thongKeModel = new DefaultTableModel(column,0);
        this.thongKeTable1.setModel(thongKeModel);
        this.thongKeTable1.setEnabled(false);
    }
    
    public int setTableContent(ObservableList<CanBo> danhSachCanBo){
        if(danhSachCanBo == null) return 0;
        String Ten,Id,NgaySinh,SoCong;
        for(CanBo cb: danhSachCanBo){
            Ten = cb.getTen();
            Id = ""+cb.getMaCanBo();
            NgaySinh = cb.getNgaySinh();
            SoCong = cb.getCong();
            thongKeModel.addRow(new Object[]{Ten,Id,NgaySinh,SoCong});
        }
        return 1;
    }
    
    public void removeAllRow(){
        thongKeModel.setRowCount(0);
    }

    public JButton getGiangDayButton() {
        return giangDayButton;
    }

    public JTable getThongKeTable1() {
        return thongKeTable1;
    }

    public JButton getNghienCuuButton() {
        return nghienCuuButton;
    }

    public JButton getTapVuButton() {
        return tapVuButton;
    }

    public JScrollPane getThongKeScrollPane() {
        return thongKeScrollPane;
    }

    public static DefaultTableModel getThongKeModel() {
        return thongKeModel;
    }

    public JButton getTatCaButton() {
        return TatCaButton;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thongKeScrollPane = new javax.swing.JScrollPane();
        thongKeTable1 = new javax.swing.JTable();
        tapVuButton = new javax.swing.JButton();
        nghienCuuButton = new javax.swing.JButton();
        giangDayButton = new javax.swing.JButton();
        TatCaButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(602, 248));

        thongKeTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        thongKeScrollPane.setViewportView(thongKeTable1);

        tapVuButton.setText("Tạp Vụ");

        nghienCuuButton.setText("Nghiên cứu");

        giangDayButton.setText("Giảng dạy");
        giangDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giangDayButtonActionPerformed(evt);
            }
        });

        TatCaButton.setText("Tất cả");
        TatCaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TatCaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nghienCuuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(giangDayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tapVuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TatCaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(thongKeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongKeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(TatCaButton)
                .addGap(18, 18, 18)
                .addComponent(tapVuButton)
                .addGap(18, 18, 18)
                .addComponent(nghienCuuButton)
                .addGap(18, 18, 18)
                .addComponent(giangDayButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void giangDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giangDayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giangDayButtonActionPerformed

    private void TatCaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TatCaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TatCaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TatCaButton;
    private javax.swing.JButton giangDayButton;
    private javax.swing.JButton nghienCuuButton;
    private javax.swing.JButton tapVuButton;
    private javax.swing.JScrollPane thongKeScrollPane;
    private javax.swing.JTable thongKeTable1;
    // End of variables declaration//GEN-END:variables
    private static DefaultTableModel thongKeModel;
}
